[package]
name = "crypto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
domain = { path = "../domain" }

argon2 = "0.5"
aes-gcm = "0.10"
jsonwebtoken = "9"
serde = "1"
serde_json = "1"
uuid = "1"
rand_core = { version = "0.6", features = ["getrandom"] }
aead = "0.6.0-rc.10"
rand = "0.10.1"
dotenvy = "0.15"